/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MRoomMember {
  avatar_url?: string | null;
  displayname?: string | null;
  is_direct?: boolean;
  join_authorised_via_users_server?: string;
  membership: "invite" | "join" | "knock" | "leave" | "ban";
  reason?: string;
  third_party_invite?: {
    display_name: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
