/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RoomSummary {
  "m.heroes"?: string[];
  "m.invited_member_count"?: number;
  "m.joined_member_count"?: number;
  [k: string]: unknown;
}
